### ISSUE TITLE
Make nix-drv-mode a real major mode

### ISSUE THREAD

**Issue by SebastienWae** [NixOS/nix-mode#117]
Is there any reason why `nix-drv-mode` is just a function and not a real major mode?
If not I can make a PR.

Currently I'm doing this:
```emacs-lisp
(use-package nix-drv-mode
  :mode ("\\.drv\\'" . nix-drv-mode)
  :config
  (define-derived-mode nix-drv-mode
  json-mode "Nix Derivation"
  "Major mode for Nix Derivations."
  :after-hook
  (progn (when (bound-and-true-p nix-prettify-mode)
	   (nix-prettify-mode -1))
	 (set-buffer-modified-p nil)
	 (read-only-mode 1))
  (setq-local inhibit-read-only t)
  (erase-buffer)
  (insert (shell-command-to-string
	   (format "%s show-derivation \"%s\""
		   nix-executable
		   (buffer-file-name))))))
```

**Comment by yorickvP** [comment]
Unlikely. Making this more idiomatic would be good. cc @matthewbauer @conao3

**Comment by conao3** [comment]
I cannot understand why I was mentiioned.  From what perspective should I comment?  Author of [leaf](https://github.com/conao3/leaf.el)?

**Comment by yorickvP** [comment]
Last one to touch nix-drv-mode :-). I see now that it was a minor edit and @matthewbauer did all the work.

**Comment by matthewbauer** [comment]
So the main reason is because I based it on elf-mode (https://github.com/abo-abo/elf-mode) which does it that way. The reason elf-mode does it this way I think is so that you can restore the buffer afterwards to just see the real text again. I didn't think there was a way to do "cleanup" after a major mode.

Cleanup is done by hexl-mode using change-major-mode-hook, though. So adding a function here should be safe if it's good enough for hexl-mode. Can you try out https://github.com/NixOS/nix-mode/pull/119?
