### ISSUE TITLE
define-obsolete-function-alias signature changed in emacs head

### ISSUE THREAD

**Issue by austinharris** [NixOS/nix-mode#125]
New emacs has made the when argument to these functions no longer optional, resulting in this error building nix-mode:

```
(wrong-number-of-arguments (3 . 4))

(#[1027 "\300\301\5\5\4F\302\6\6\6\6\6\6FE\207" [progn defalias make-obsolete] 10 1985393] 'global-nix-prettify-mode 'nix-prettify-global-mode)
```

**Comment by austinharris** [comment]
Will be resolved by https://github.com/NixOS/nix-mode/pull/122

**Comment by JeffreyBenjaminBrown** [comment]
I just solved this problem in [my own configuration](https://github.com/JeffreyBenjaminBrown/nixos-experiments/tree/01c5bfada73d425a1723dd66ec9b6355c5180d43/config) (that's an absolute link, so it will not update with new commits) by obtaining `nix-mode` from `epkgs.melpaPackages` rather than ``epkgs.melpaStablePackages`. Mentioning just in case others run into the same issue.

Maybe if (as is true) I'm on the `unstable` branch of `nixpkgs` I should only be using melpa, and not melpaStable?
