### ISSUE TITLE
Smie indent mode overrides function globally

### ISSUE THREAD

**Issue by jD91mZM2** [NixOS/nix-mode#95]
I'm trying to create a custom major mode using smie, and found after a loong painful debugging session and multiple emacs restarts, that [this function override](https://github.com/NixOS/nix-mode/blob/5b5961780f3b1c1b62453d2087f775298980f10d/nix-mode.el#L973) somehow affects a buffer that has nothing to do with Nix and nix-mode. `C-h f smie-indent-exps` claims to be from `smie.el`, but after closer inspection it actually has `nix-smie--indent-exps`'s description. I'm guessing you can't make symbols buffer only like you're trying to, but my emacs-fu isn't so strong as to immediately recognize what might be wrong. Maybe the new function definition could check if the major mode really is nix-mode before proceeding?

**Comment by matthewbauer** [comment]
Yeah this looks like an issue. It looks like you can't  I think instead of overriding that function we can maybe just set `smie-indent-functions` to what values we want. /cc @j-piecuch

**Comment by jahkeup** [comment]
I have a workaround that *replaces* elements in the list of functions instead of overriding the original functions. I'd be happy to clean up the patch and contribute it if it fixes the problem that @jD91mZM2 is seeing.

https://github.com/jahkeup/nix-mode/blob/5fe4993b13a6c4c1c7fc686522f84c9460ec7e0a/nix-mode.el#L974-L980

**Comment by matthewbauer** [comment]
Looks good! I applied it in 28e83dd56bf2355918739eb41f2eabd860ec7566
